language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
  - "pip install importlib"
  - "pip install -e ."
script:
  - "flake8 src/"
  - "python setup.py nosetests"
notifications:
  email: false
